title: Homepage of Adrian&nbsp;Röllin
logo: /img/adrianroellin_portrait_web.jpg
description: <br>Prof. Adrian Röllin<br>Department of Statistics and Data Science<br>National University of Singapore<br>6 Science Drive 2<br>Singapore 117546
e-mail: adrian.roellin@nus.edu.sg
google_analytics: "1T-bWHH_qjAsaLMDmY-tZJeuaI71UMSfNVcg8ynnW6s"
theme: jekyll-theme-minimal
